workflows:
  - name: checks
    # This is needed because the `cd.yml` has a minor manual modification.
    # This job will be re-activated in:
    #   https://github.com/exasol/integration-test-docker-environment/issues/630
    remove_jobs:
      - check-workflows
