#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

pushd "$SCRIPT_DIR" &> /dev/null

if [[ -t 1 ]]
then
  terminal_parameter=-it
else
  terminal_parameter=""
fi

quoted_arguments=''
for argument in "$@"
do
    argument="${argument//\\/\\\\}"
    quoted_arguments="$quoted_arguments \"${argument//\"/\\\"}\""
done

docker run --rm $terminal_parameter -v "$PWD:$PWD" -v /var/run/docker.sock:/var/run/docker.sock -w "$PWD" exatk/script-languages:test_environment_docker_runner bash -c "source /venv/bin/activate && ./start-test-env-without-docker-runner $quoted_arguments && chown -R $(id -u):$(id -g) .build_output &> /dev/null"

return_code="$?"

popd &> /dev/null

exit $return_code
