#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

pushd "$SCRIPT_DIR" &> /dev/null

if [[ -t 1 ]]
then
  terminal_parameter=-it
else
  terminal_parameter=""
fi

quoted_arguments=''
for argument in "${@}"
do
    argument="${argument//\\/\\\\}"
    quoted_arguments="$quoted_arguments \"${argument//\"/\\\"}\""
done

IMAGE_NAME=$("$SCRIPT_DIR/scripts/docker/construct_docker_runner_image_name.sh")

docker pull "$IMAGE_NAME" || bash "$SCRIPT_DIR/scripts/docker/build_test_environment_docker_runner.sh"

docker run --rm $terminal_parameter -v "$PWD:$PWD" -v /var/run/docker.sock:/var/run/docker.sock -w "$PWD" "$IMAGE_NAME" bash -c "python3 -m pip install .; ./start-test-env-without-poetry $quoted_arguments; RETURN_CODE=\$?; chown -R $(id -u):$(id -g) .build_output &> /dev/null; exit \$RETURN_CODE"

popd &> /dev/null
