#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

export PYTHONPATH="$SCRIPT_DIR"
python3 "$SCRIPT_DIR/exasol_integration_test_docker_environment/main.py" "${@}" # We use "$@" to pass the commandline arguments to the run function to preserve arguments with spaces as a single argument
exit $?
