#!/bin/bash

# This script acts as the start of exaslct the script language container build tool
# It tries to discover if pipenv is already installed or tries to install it if it not exists.
# After that it creates the virtual environment and install all necessary dependencies for exaslct.
# In the end it runs exaslct_src/exaslct.py in the virtual environment.


SCRIPT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

source "$SCRIPT_DIR/pipenv_utils.sh"

run () {
    export PYTHONPATH="$SCRIPT_DIR"
    $PIPENV_BIN run python3 "$SCRIPT_DIR/src/main.py" "$@" # We use "$@" to pass the commandline arguments to the run function to preserve arguments with spaces as a single argument

}

discover_pipenv
init_pipenv "$PIPENV_BIN"
if [ -n "$PIPENV_BIN" ]
then
  run "$@" # We use "$@" to pass the commandline arguments to the run function to preserve arguments with spaces as a single argument
else
  echo "Could not find pipenv!"
  exit 1
fi
