/* *
 * PREPARE
 * */

INSERT INTO STAGE.KUNDEN (KUNDENNUMMER, VORNAME, NACHNAME, GEBURTSDATUM, URSPRUNG_EINGANGSKANAL, REGION, LETZTER_KONTAKT) 
VALUES(0, 'SIMON', 'DUDANSKI', '1987-04-15', 'SLACK', 'HAMBURCH', '2020-06-22');

INSERT INTO STAGE.INTERESSENTEN (VORGANGSNUMMER, VORNAME, NACHNAME, GEBURTSDATUM, EINGANGSKANAL, REGION, BERATUNGSTERMIN) 
VALUES(0, 'CARSTEN', 'WEIDMANN', '1980-01-01', 'WEBEX', 'BAYERN', '2020-06-22');


 CREATE OR REPLACE TABLE CLEANSE.T_RESULT_testSql1
(ID DECIMAL (18,0)
       ,REGION VARCHAR(256)
       ,ALTERSGRUPPE VARCHAR(20)
       ,EINGANGSKANAL VARCHAR(256)
       ,IST_KUNDE BOOLEAN
       ,LETZTER_KONTAKT VARCHAR(256));


IMPORT INTO CLEANSE.T_RESULT_testSql1
      FROM LOCAL CSV  FILE '/test/testSQL1/V_PERSON.csv'
     COLUMN SEPARATOR = ',' SKIP = 1;

/* *
 * RUN
 * */



 
SELECT 1/CASE WHEN COUNT(1) > 0 THEN 0 ELSE 1 END FROM
(
		(SELECT p.ID, p.REGION, p.ALTERSGRUPPE, p.EINGANGSKANAL, p.IST_KUNDE, p.LETZTER_KONTAKT 
		FROM CLEANSE.V_PERSON p
		MINUS
		SELECT r.ID, r.REGION, r.ALTERSGRUPPE, r.EINGANGSKANAL, r.IST_KUNDE, r.LETZTER_KONTAKT 
		FROM CLEANSE.T_RESULT_testSql1 r)
		UNION
		(SELECT r.ID, r.REGION, r.ALTERSGRUPPE, r.EINGANGSKANAL, r.IST_KUNDE, r.LETZTER_KONTAKT 
		FROM CLEANSE.T_RESULT_testSql1 r
		MINUS
		SELECT p.ID, p.REGION, p.ALTERSGRUPPE, p.EINGANGSKANAL, p.IST_KUNDE, p.LETZTER_KONTAKT 
		FROM CLEANSE.V_PERSON p)
);
 

/* *
 * CLEAN UP
 * */

 TRUNCATE TABLE STAGE.KUNDEN;
 TRUNCATE TABLE STAGE.INTERESSENTEN;
 DROP TABLE CLEANSE.T_RESULT_testSql1;
