CREATE SCHEMA IF NOT EXISTS STAGE;

CREATE OR REPLACE TABLE STAGE.KUNDEN 
( KUNDENNUMMER DECIMAL(8,0)
 ,VORNAME VARCHAR(512)
 ,NACHNAME VARCHAR(512)
 ,GEBURTSDATUM DATE
 ,URSPRUNG_EINGANGSKANAL VARCHAR(256)
 ,REGION  VARCHAR(256)
 ,LETZTER_KONTAKT VARCHAR(256)
);

CREATE OR REPLACE TABLE STAGE.INTERESSENTEN 
( VORGANGSNUMMER DECIMAL(8,0)
 ,VORNAME VARCHAR(512)
 ,NACHNAME VARCHAR(512)
 ,GEBURTSDATUM DATE
 ,EINGANGSKANAL VARCHAR(256)
 ,REGION  VARCHAR(256)
 ,BERATUNGSTERMIN VARCHAR(256)
);
