CREATE OR REPLACE VIEW CLEANSE.V_PERSON AS 
SELECT ROW_NUMBER() OVER (PARTITION BY 1 ORDER BY ID, IST_KUNDE) AS ID
      ,REGION
      ,ALTERSGRUPPE
      ,EINGANGSKANAL 
      ,IST_KUNDE
      ,LETZTER_KONTAKT
 FROM (
       SELECT KUNDENNUMMER AS ID
             ,REGION AS REGION
             ,CAST(CAST(ROUND((CURRENT_DATE-GEBURTSDATUM)/3650,0)*10 AS VARCHAR(3))
             ||' - '||CAST(ROUND((CURRENT_DATE-GEBURTSDATUM)/3650,0)*10+10 AS VARCHAR(3)) AS VARCHAR(20)) AS ALTERSGRUPPE
             ,URSPRUNG_EINGANGSKANAL AS EINGANGSKANAL
             ,TRUE AS IST_KUNDE
             ,LETZTER_KONTAKT
         FROM STAGE.KUNDEN
      UNION
      SELECT VORGANGSNUMMER AS ID
             ,REGION AS REGION
             ,CAST(CAST(ROUND((CURRENT_DATE-GEBURTSDATUM)/3650,0)*10 AS VARCHAR(3))
             ||' - '||CAST(ROUND((CURRENT_DATE-GEBURTSDATUM)/3650,0)*10+10 AS VARCHAR(3)) AS VARCHAR(20)) AS ALTERSGRUPPE
             ,EINGANGSKANAL
             ,FALSE AS IST_KUNDE
             ,BERATUNGSTERMIN AS LETZTER_KONTAKT
         FROM STAGE.INTERESSENTEN
);