name: CD

on:
  push:
    tags:
      - '**'

jobs:

  check-tag-version-job:
    name: Check Release Tag
    uses: ./.github/workflows/check-release-tag.yml
    permissions:
      contents: read

  cd-job:
    needs: [ check-tag-version-job ]
    name: Continuous Delivery
    uses: ./.github/workflows/build-and-publish.yml
    permissions:
      contents: write
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

  standalone-executable:
    needs: [cd-job]
    name: Create a standalone linux executable
    uses: ./.github/workflows/build-executable.yml
    with:
      release-tag: ${{ github.ref_name }}
    permissions:
      contents: write

  publish-docs:
    needs: [ cd-job ]
    name: Publish Documentation
    uses: ./.github/workflows/gh-pages.yml
    permissions:
      contents: read
      pages: write
      id-token: write
