name: Check if versions are consistent

on: pull_request

jobs:
  check-version-numbers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare_poetry_env
      - name: Check Release
        run: ./scripts/build/check_release.sh
