name: Check Release Tag

on:
  workflow_call:

jobs:

  check-tag-version-job:
    name: Check Tag Version
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: SCM Checkout
        uses: actions/checkout@v4

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@refactoring/553_530_fix_poeytry_gh_action_and_min_versioned_refs

      - name: Check Tag Version
        # make sure the pushed/created tag matched the project version
        run: "[[ `poetry version --short` == ${{ github.ref_name }} ]]"
