name: CI

on:
  pull_request:

jobs:

  checks:
    name: Checks
    uses: ./.github/workflows/checks.yml

  slow-tests-approval:
    name: Slow
    runs-on: ubuntu-latest

    # Even though the environment "manual-approval" will be created automatically,
    # it still needs to be configured to require interactive review.
    # See project settings on GitHub (Settings / Environments / manual-approval).
    environment: manual-approval

    # Replace the steps below with the required actions
    # and/or add additional jobs if required
    # Note:
    #   If you add additional jobs, make sure they are added as a requirement
    #   to the approve-merge job's input requirements (needs).
    steps:
      - name: Tests
        run: |
          echo "Slow tests approved"

  slow-tests:
    needs: slow-tests-approval
    name: Slow Tests
    uses: ./.github/workflows/slow_tests.yml

  fast-tests:
    name: Fast Tests
    uses: ./.github/workflows/fast_tests.yml

  metrics:
    needs: [ fast-tests, checks ]
    uses: ./.github/workflows/report.yml

  # This job ensures inputs have been executed successfully.
  approve-merge:
    name: Allow Merge
    runs-on: ubuntu-latest
    # If you need additional jobs to be part of the merge gate, add them below
    needs: [ metrics, slow-tests ]

    # Each job requires a step, so we added this dummy step.
    steps:
      - name: Approve
        run: |
          echo "Merge Approved"

