name: Generate release documentation

on:
  release:
    types: [published]
jobs:

  publish-release-documentation:
    runs-on: ubuntu-latest

    environment: publish

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: ./.github/actions/prepare_poetry_env
    - name: Deploy release documentation to github-pages branch
      run: |
        git config --local user.email "opensource@exasol.com"
        git config --local user.name "GitHub Action"
        git fetch
        poetry run python -m nox -s push-pages-release