name: Fast-Tests-Extension

on:
  workflow_call:

jobs:
  EXAConf-files:
    name: Test EXAConf files
    permissions:
      contents: read
    uses: ./.github/workflows/test-exaconf-files.yml

  test-shell-scripts:
    name: Test Shell Scripts
    permissions:
      contents: read
    uses: ./.github/workflows/test-shell-scripts.yml
