name: Fast Tests

on:
  workflow_call:
    secrets:
      ALTERNATIVE_GITHUB_TOKEN:
        required: false

jobs:
  build-matrix:
    name: Generate Build Matrix
    uses: ./.github/workflows/matrix-python.yml

  fast-tests:
    name: Unit-Tests (Python-${{ matrix.python-version }}, Exasol-${{ matrix.exasol-version}})
    needs: [ build-matrix ]
    runs-on: ubuntu-24.04
    env:
      GITHUB_TOKEN: ${{ secrets.ALTERNATIVE_GITHUB_TOKEN ||  secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v4

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@1.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Tests and Collect Coverage
        run: poetry run nox -s test:unit -- -- --coverage

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.4.0
        with:
          name: coverage-python${{ matrix.python-version }}-fast
          path: .coverage
          include-hidden-files: true

  db-version-minimal-tests:
    name: Run Db Versions Minimal Tests
    uses: ./.github/workflows/test-db-versions-minimal.yml

  test-docker-starter:
    name: Test Docker Starter
    uses: ./.github/workflows/test-docker-starter.yml

  test-shell-scripts:
    name: Test Shell Scripts
    uses: ./.github/workflows/test-shell-scripts.yml
