on:
  workflow_call:
    outputs:
      matrix:
        description: "The list of known db versions"
        value: ${{ jobs.get_exasol_versions.outputs.matrix }}
jobs:
  get_exasol_versions:
    runs-on: ubuntu-latest
    steps:
      - name: SCM Checkout
        uses: actions/checkout@v4

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@0.17.0
        with:
          python-version: "3.10"
          poetry-version: '1.8.2'

      - name: Print matrix
        run: poetry run nox --non-interactive -s "get-all-db-versions"

      - id: set-matrix
        run: |
          ALL_DB_VERSIONS=`poetry run nox --non-interactive -s 'get-all-db-versions'` 
          echo "matrix=$ALL_DB_VERSIONS" >> "$GITHUB_OUTPUT"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
