name: Merge-Gate-Extension

on:
  workflow_call:

jobs:
  standalone-executable:
    name: Create a standalone linux executable
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: SCM Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v6
        with:
          python-version: "3.10"
          poetry-version: "2.3.0"

      - name: Build standalone executable
        run: poetry run -- nox -s build-standalone-binary -- --executable-name "itde_linux_x86-64"

      - name: Execute the executable
        run: poetry run -- nox -s execute-itde -- --executable-name "dist/itde_linux_x86-64"
