name: Periodic Validation

on:
  schedule:
    # “At 00:00 on every 7th day-of-month from 1 through 31.” (https://crontab.guru)
    - cron: "0 0 1/7 * *"

jobs:

  checks:
    name: Checks
    uses: ./.github/workflows/checks.yml

  slow-tests:
    name: Slow Tests
    uses: ./.github/workflows/slow_tests.yml

  fast-tests:
    name: Slow Tests
    uses: ./.github/workflows/fast_tests.yml

  metrics:
    needs: [ fast-tests, checks ]
    uses: ./.github/workflows/report.yml

