name: PR-Merge

on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:

  # This job can be removed if certain preconditions are met. See
  # https://exasol.github.io/python-toolbox/user_guide/workflows.html#pr-merge-workflow

  checks:
    name: Checks
    uses: ./.github/workflows/checks.yml

  fast-tests:
    name: Fast Tests
    uses: fast-tests.yml

  metrics:
    name: Report Metrics
    needs: [ checks, fast-tests ]
    uses: ./.github/workflows/report.yml

  publish-docs:
    name: Publish Documentation
    uses: ./.github/workflows/gh-pages.yml

  publish-docker-runner:
    name: Publish Runner Docker Image to Dockerhub
    uses: publish-docker-runner.yml
    secrets:
      DOCKER_USER_NAME: ${{ secrets.DOCKER_USER_NAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
