name: Publish Docker Runner

on:
 workflow_call:
    secrets:
      DOCKER_USER_NAME:
          required: true
      DOCKER_TOKEN:
          required: true

jobs:
  publish:
    runs-on: ubuntu-24.04
    environment: publish
    permissions:
      contents: read
    steps:

      - name: SCM Checkout
        uses: actions/checkout@v4

      - name: Build new Docker image
        run: bash ./starter_scripts/build_docker_runner_image.sh

      - name: Docker login
        run: echo "$SECRET_DOCKER_TOKEN" | docker login --username "$SECRET_DOCKER_USER_NAME" --password-stdin
        env: # Set the secret as an input
          SECRET_DOCKER_USER_NAME: ${{ secrets.DOCKER_USER_NAME }}
          SECRET_DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

      - name: Push new Docker image
        if: github.ref == 'refs/heads/main'
        run: bash ./starter_scripts/push_docker_runner_image.sh

      - name: Push new ci-release-test Docker image
        if: github.ref != 'refs/heads/main'
        run: bash ./starter_scripts/push_docker_runner_image.sh "ci-release-test"
