name: Publish Docker Runner

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish
    steps:
    - uses: actions/checkout@v2
    - name: Build new Docker image
      run: bash ./scripts/docker/build_test_environment_docker_runner.sh
    - name: Docker login
      run: echo "$SECRET_DOCKER_TOKEN" | docker login --username "$SECRET_DOCKER_USER_NAME" --password-stdin 
      env: # Set the secret as an input
        SECRET_DOCKER_USER_NAME: ${{ secrets.DOCKER_USER_NAME }}
        SECRET_DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    - name: Push new Docker image
      run: bash ./scripts/docker/push_test_environment_docker_runner.sh

