name: Publish Docker Runner

on:
  push:
    branches:
      - master
      - 'ci-release-test/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish
    steps:
    - uses: actions/checkout@v2
    - name: Build new Docker image
      run: bash ./starter_scripts/build_docker_runner_image.sh
    - name: Docker login
      run: echo "$SECRET_DOCKER_TOKEN" | docker login --username "$SECRET_DOCKER_USER_NAME" --password-stdin 
      env: # Set the secret as an input
        SECRET_DOCKER_USER_NAME: ${{ secrets.DOCKER_USER_NAME }}
        SECRET_DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    - name: Push new Docker image
      if: github.ref == 'refs/heads/master'
      run: bash ./starter_scripts/push_docker_runner_image.sh
    - name: Push new ci-release-test Docker image
      if: github.ref != 'refs/heads/master'
      run: bash ./starter_scripts/push_docker_runner_image.sh "ci-release-test"

