name: Build & Publish

on:
  push:
    tags: '**'

  workflow_dispatch:

jobs:

  cd-job:
    name: Continues Delivery
    runs-on: ubuntu-latest
    steps:

      - name: SCM Checkout
        uses: actions/checkout@v3

      - name: Setup Python & Poetry Environment
        uses: ./.github/actions/prepare_poetry_env

      - name: Build Artifacts
        run: poetry build

      - name: PyPi Release
        env:
          POETRY_HTTP_BASIC_PYPI_USERNAME: "__token__"
          POETRY_HTTP_BASIC_PYPI_PASSWORD: "${{ secrets.PYPI_TOKEN }}"
        run: poetry publish

      - name: GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh release create ${GITHUB_REF_NAME}
          --title ${GITHUB_REF_NAME} -F "./doc/changes/changes_${GITHUB_REF_NAME}.md"
          dist/*
