name: Release Droid - Upload GitHub Release Assets

on:
  workflow_dispatch:
    inputs:
      upload_url:
        description: 'Upload URL'
        required: true

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python 3.8 for integration-test-docker-environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.2.0

      - name: Check Release
        run: ./scripts/build/check_release.sh

  test-docker-starter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build new Docker image
      run: bash ./starter_scripts/build_docker_runner_image.sh

    - name: Test ./start-test-env
      run: ./start-test-env --help

  upload:
    needs: [test-docker-starter, check-release]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Poetry
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: 1.2.0

    - name: Build Release
      run: |
        bash ./scripts/build/build_release.sh

    - name: Upload assets to the GitHub release draft
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ github.event.inputs.upload_url }}
        asset_path: dist/*
