name: Slow Tests

on:
  workflow_call:

jobs:

  test-db-versions-all-tests:
    name: Run all tests with all supported Db Versions
    uses: ./.github/workflows/test-db-versions-all-tests.yml

  test-python-versions:
    name: Run all tests with all supported Python versions
    uses: ./.github/workflows/test-python-versions.yml

  db-version-gpu-tests:
    name: Run Db Versions GPU Tests
    uses: ./.github/workflows/test-db-versions-gpu.yml
