name: Test Python Versions with all tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-python-version-all-tests:
    strategy:
      fail-fast: false
      matrix:
        exasol_version:
        - "default"
        python_version:
        - 3.8
        - 3.9
    name: Run tests with Python ${{ matrix.python_version }} and Exasol ${{ matrix.exasol_version }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/prepare_poetry_env
      with:
        python_version: "${{ matrix.python_version }}"
    - name: Run all tests
      run: poetry run nox -s "run-tests(${{ matrix.exasol_version }})"
