name: Test DB Versions with minimal tests

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  get_exasol_versions:
    uses: ./.github/workflows/get_exasol_versions.yml

  test-db-versions-minimal:
    needs: get_exasol_versions
    strategy:
      fail-fast: false
      matrix:
        exasol_version: ${{fromJson(needs.get_exasol_versions.outputs.matrix)}}
    runs-on: ubuntu-latest
    name: Run minimum tests for Exasol ${{ matrix.exasol_version }}
    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/prepare_poetry_env

    - name: Run minimal tests
      run: poetry run nox -s "run-minimal-tests(db_version='${{ matrix.exasol_version }}')"
