name: Test DB Versions with minimal tests

# python-version: default as specified
# database-version: all supported by ITDE
# tests: minimal (subset of all tests)
#
# Use the specified default version of python and call nox task
# run_minimal_tests to execute a few selected tests for all versions of Exasol
# database currently supported by the ITDE.

on:
 workflow_call:

jobs:
  build_matrix:
    permissions:
      contents: read
    uses: ./.github/workflows/matrix.yml
    with:
      matrix_keys_json: '["db_versions"]'

  test-db-versions-minimal:
    name: Run Minimal Tests for Exasol ${{ matrix.db_versions }} (Python ${{ matrix.python-versions }})
    needs: build_matrix
    strategy:
      fail-fast: false
      matrix:
        python-versions: ["3.10", "3.14"]
        db_versions: ${{ fromJson(needs.build_matrix.outputs.matrix).db_versions }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: SCM Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v6
        with:
          python-version: ${{ matrix.python-versions }}
          poetry-version: "2.3.0"

      - name: Allow unprivileged user namespaces
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Run Minimal Tests
        run: poetry run -- nox -s run-minimal-tests -- --db-version=${MATRIX_DB_VERSION} --test-set=default
        env:
          MATRIX_DB_VERSION: ${{ matrix.db_versions }}