name: Test Python Versions with all tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-python-version-all-tests:
    strategy:
      fail-fast: false
      matrix:
        exasol_version:
        - "default"
        python_version:
        - "3.9"
        - "3.10"
    name: Run tests with Python ${{ matrix.python_version }} and Exasol ${{ matrix.exasol_version }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python & Poetry Environment
      uses: exasol/python-toolbox/.github/actions/python-environment@0.17.0
      with:
        python-version: ${{ matrix.python_version }}
        poetry-version: '1.8.2'
    - name: Run all tests
      run: poetry run nox -s "run-tests(db_version='${{ matrix.exasol_version }}')"
