name: Test Python Versions with all tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-python-version-all-tests:
    strategy:
      fail-fast: false
      matrix:
        exasol_version:
        - "default"
        python_version:
        - 3.8
        - 3.9
    name: Run tests with Python ${{ matrix.python_version }} and Exasol ${{ matrix.exasol_version }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python for integration-test-docker-environment
      uses: actions/setup-python@v2
      with:
        python-version: "${{ matrix.python_version }}"

    - name: Install Poetry
      uses: abatilo/actions-poetry@v2.1.4
      with:
        poetry-version: 1.1.11

    - name: Run all tests
      run: ./scripts/test/run_all_tests.sh
      env:
        EXASOL_VERSION: "${{ matrix.exasol_version }}"
