name: Test Docker Starter

on:
  workflow_call:

jobs:
  test-docker-starter:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: SCM Checkout
        uses: actions/checkout@v4

      - name: Test ./start-test-env
        run: ./start-test-env health
