name: Test DB Versions with all tests

on:
 workflow_call:

jobs:
  get_exasol_versions:

    uses: ./.github/workflows/get_exasol_versions.yml

  test-db-versions-all-tests:
    needs: get_exasol_versions
    strategy:
      fail-fast: false
      matrix:
        exasol_version: ${{fromJson(needs.get_exasol_versions.outputs.matrix)}}
    runs-on: ubuntu-latest
    name: Run all tests for Exasol ${{ matrix.exasol_version }}
    steps:
      - name: SCM Checkout
        uses: actions/checkout@v4

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@0.17.0
        with:
          python-version: "3.10"
          poetry-version: '1.8.2'

      - name: Allow unprivileged user namespaces
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Run all tests
        run: poetry run nox -s "run-tests(db_version='${{ matrix.exasol_version }}')"
