name: Test Docker Starter

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-docker-starter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Test ./start-test-env
      run: ./start-test-env --help
