name: Test Python Versions with all tests

# python-version: All supported Python version
# database-version: Default
# tests: all
# platform: default
#
# Call nox task run_tests for all version of Python as defined in the
# python-toolbox (PTB) using the default version of the Exasol database.

on:
  workflow_call:

jobs:
  get_test_runners:
    name: Read all additional test runners
    permissions:
      contents: read
    uses: ./.github/workflows/get-test-runner.yml
    with:
      runner_type: only_default

  build-matrix:
    name: Generate Build Matrix
    permissions:
      contents: read
    uses: ./.github/workflows/matrix-python.yml

  test-python-version-all-tests:
    name: "Run Tests with Python ${{ matrix.python-version }} and Default Exasol Version on ${{matrix.runner}}"
    permissions:
      contents: read
    needs:
      - get_test_runners
      - build-matrix
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJson(needs.build-matrix.outputs.matrix) }}.python-version
        runner: ${{ fromJson(needs.get_test_runners.outputs.matrix) }}
    runs-on: ${{matrix.runner}}
    steps:
      - name: SCM Checkout
        uses: actions/checkout@v6

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v5
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: "2.3.0"

      - name: Allow unprivileged user namespaces
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Run all tests
        run: poetry run -- nox -s run-all-tests -- --db-version=default --test-set=default
