name: Test Python Versions with all tests

# python-version: All supported Python version
# database-version: Default
# tests: all
#
# Call nox task run_tests for all version of Python as defined in the
# python-toolbox (PTB) using the default version of the Exasol database.

on:
  workflow_call:

jobs:

  build_matrix:
    name: Generate Build Matrix
    permissions:
      contents: read
    uses: ./.github/workflows/matrix.yml
    with:
      matrix_keys_json: '["python_versions"]'

  test-python-version-all-tests:
    name: "Run Tests with Python ${{ matrix.python_versions }} and Default Exasol Version"
    permissions:
      contents: read
    needs: build_matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build_matrix.outputs.matrix) }}
    runs-on: ubuntu-24.04
    steps:
      - name: SCM Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v6
        with:
          python-version: ${{ matrix.python_versions }}
          poetry-version: "2.3.0"

      - name: Allow unprivileged user namespaces
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Run all tests
        run: poetry run -- nox -s run-all-tests -- --db-version=default --test-set=default
