name: Test DB Versions with all tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  get_exasol_versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install jq
        run: sudo apt-get install jq
      - name: Print matrix
        run: bash ./scripts/test/get_exasol_versions.sh
      - id: set-matrix
        run: |
          echo "::set-output name=matrix::$(bash ./scripts/test/get_exasol_versions.sh)"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  test-db-versions-all-tests:
    needs: get_exasol_versions
    strategy:
      fail-fast: false
      matrix:
        exasol_version: ${{fromJson(needs.get_exasol_versions.outputs.matrix)}}
    runs-on: ubuntu-latest
    name: Run all tests for Exasol ${{ matrix.exasol_version }}
    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/prepare_poetry_env

    - name: Fail, because not all tests are activated
      run: |
        git fetch
        GIT_LOG="$(git log --pretty=oneline --abbrev-commit ${{ github.event.after }} | head -n 1)"
        echo "$GIT_LOG"
        if [[ "$GIT_LOG" == *"[run all tests]"* ]]; then
          echo "All tests activated"
          exit 0
        else
          echo "Fail, because not all tests are deactivated"
          exit 1
        fi
      env:
        EXASOL_VERSION: "${{ matrix.exasol_version }}"
      # We want to deactivate running all tests only for pull_requests
      if: ${{ github.event_name == 'pull_request' }}

    - name: Run all tests
      run: poetry run nox -s "run-tests(db_version='${{ matrix.exasol_version }}')"
