name: Test DB Versions with minimal tests

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  get_exasol_versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          sudo apt-get install jq
          echo "::set-output name=matrix::$(bash ./scripts/test/get_exasol_versions.sh)"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  test-db-versions-minimal:
    strategy:
      fail-fast: false
      matrix:
        exasol_version: ${{fromJson(needs.get_exasol_versions.outputs.matrix)}}
    runs-on: ubuntu-latest
    name: Run minimum tests for Exasol ${{ matrix.exasol_version }}
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python 3.6 for integration-test-docker-environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install Poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1.6

    - name: Run minimal tests
      run: |
          ./scripts/test/run_test.sh exasol_integration_test_docker_environment/test/test_test_environment.py
          ./scripts/test/run_test.sh exasol_integration_test_docker_environment/test/test_doctor.py
      env:
        EXASOL_VERSION: "${{ matrix.exasol_version }}"
