name: Tests

on:
  workflow_call:
    secrets:
      ALTERNATIVE_GITHUB_TOKEN:
        required: false

jobs:
  build-matrix:
    name: Generate Build Matrix
    uses: ./.github/workflows/matrix-python.yml

  Tests:
    name: Unit-Tests (Python-${{ matrix.python-version }}, Exasol-${{ matrix.exasol-version}})
    needs: [ build-matrix ]
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ALTERNATIVE_GITHUB_TOKEN ||  secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v4

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@0.20.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Tests and Collect Coverage
        run: poetry run nox -s test:unit -- -- --coverage

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.4.0
        with:
          name: coverage-python${{ matrix.python-version }}-fast
          path: .coverage
          include-hidden-files: true

  Db-Version-Minimal-Tests:
    uses: ./.github/workflows/test_db_versions_minimal.yml
  Test-Docker-Starter:
    uses: ./.github/workflows/test_docker_starter.yml
  Test-Shell-Scripts:
    uses: ./.github/workflows/test_shell_scripts.yml
  Slow-Tests:
    name: Slow
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    # Even though the environment "manual-approval" will be created automatically,
    # it still needs to be configured to require interactive review.
    # See project settings on GitHub (Settings / Environments / manual-approval).
    environment: manual-approval

    # Replace the steps below with the required actions
    # and/or add additional jobs if required
    # Note:
    #   If you add additional jobs, make sure they are added as a requirement
    #   to the approve-merge job's input requirements (needs).
    steps:
      - name: Tests
        run: |
          echo "Slow tests approved"
  Test-Db-Versions-All-Tests:
    needs: Slow-Tests
    uses: ./.github/workflows/test_db_versions_all_tests.yml
  Test-Python-Versions:
    needs: Slow-Tests
    uses: ./.github/workflows/test_python_version.yml
