name: Test Python Versions with all tests

# python-version: All supported Python version
# database-version: Default
# tests: all (dynamic matrix)
#
# Execute one dynamic test target per matrix entry for all supported Python
# versions using the default Exasol database version.

on:
  workflow_call:

jobs:

  build_matrix:
    name: Generate Build Matrix
    permissions:
      contents: read
    uses: ./.github/workflows/matrix.yml
    with:
      matrix_keys_json: '["slow_python_test_matrix"]'

  test-python-version-all-tests:
    name: "Run Tests with Python ${{ matrix.python_versions }} - ${{ matrix.integration_test_targets }}"
    permissions:
      contents: read
    needs: build_matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build_matrix.outputs.matrix).slow_python_test_matrix }}
    runs-on: ubuntu-24.04
    steps:
      - name: SCM Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v6
        with:
          python-version: ${{ matrix.python_versions }}
          poetry-version: "2.3.0"

      - name: Allow unprivileged user namespaces
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Run all tests
        if: ${{ !matrix.collect_coverage }}
        run: poetry run -- nox -s run-integration-tests -- --db-version=default --test-target=${MATRIX_TEST_TARGET}
        env:
          MATRIX_TEST_TARGET: ${{ matrix.integration_test_targets }}

      - name: Run all tests with coverage
        if: ${{ matrix.collect_coverage }}
        run: poetry run -- nox -s run-integration-tests -- --db-version=default --test-target=${MATRIX_TEST_TARGET} --coverage
        env:
          MATRIX_TEST_TARGET: ${{ matrix.integration_test_targets }}

      - name: Upload Coverage Artifact
        if: ${{ matrix.collect_coverage }}
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.coverage_artifact_name }}
          path: .coverage
          include-hidden-files: true
          overwrite: false
