name: Tests

on:
  workflow_call:
    secrets:
      ALTERNATIVE_GITHUB_TOKEN:
        required: false

jobs:

  Tests:
    name: Tests (Python-${{ matrix.python-version }}, Exasol-${{ matrix.exasol-version}})
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ALTERNATIVE_GITHUB_TOKEN ||  secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        exasol-version: ["7.1.9"]

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v4

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@0.17.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Unit Tests
        run: poetry run nox -s test:unit

      - name: Run Unit Tests
        run: poetry run coverage report -m

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.4.0
        with:
          name: coverage-python${{ matrix.python-version }}
          path: .coverage
          include-hidden-files: true

  Slow-Tests:
    name: Slow
    runs-on: ubuntu-latest

    # Even though the environment "manual-approval" will be created automatically,
    # it still needs to be configured to require interactive review.
    # See project settings on GitHub (Settings / Environments / manual-approval).
    environment: manual-approval

    # Replace the steps below with the required actions
    # and/or add additional jobs if required
    # Note:
    #   If you add additional jobs, make sure they are added as a requirement
    #   to the approve-merge job's input requirements (needs).
    steps:
      - name: Tests
        run: |
          echo "Slow tests ran successfully"
