name: Test DB Versions with minimal tests

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  get_exasol_versions:
    uses: ./.github/workflows/get_exasol_versions.yml

  test-db-versions-minimal:
    needs: get_exasol_versions
    strategy:
      fail-fast: false
      matrix:
        exasol_version: ${{fromJson(needs.get_exasol_versions.outputs.matrix)}}
    runs-on: ubuntu-latest
    name: Run minimum tests for Exasol ${{ matrix.exasol_version }}
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python & Poetry Environment
      uses: exasol/python-toolbox/.github/actions/python-environment@0.17.0
      with:
        python-version: "3.10"
        poetry-version: '1.8.2'

    - name: Run minimal tests
      run: poetry run nox -s "run-minimal-tests(db_version='${{ matrix.exasol_version }}')"
