name: update-docu

on:
  push:
    branches:
      - main

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare_poetry_env

      - name: Publish Documentation
        run: |
          git config --local user.email "opensource@exasol.com"
          git config --local user.name "GitHub Action"
          git fetch
          poetry run python3 -m nox -s push-pages-main
