name: validate-docu

on:
  push:
    branches-ignore:
      - "github-pages/*"
      - "main"

jobs:
  validate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/prepare_poetry_env
      - name: Build Documentation
        run: poetry run python -m nox -s build-html-doc

