name: 'Prepare Poetry environment'
description: 'This composite actions checkouts out the project, installs Poetry, and install the project in the Poetry environment'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: abatilo/actions-poetry@v2
      with:
        poetry-version: 1.2.0
    - name: Poetry install
      run: poetry install
      shell: bash
